# Static

- type: latheRecipePack
  id: ImpLightPack
  recipes:
    - UvLightTube
    - DeskBell
    - LightReplacer

- type: latheRecipePack
  id: ImpServiceStatic
  recipes:
    - Mousetrap
    - TrashBag

- type: latheRecipePack
  id: CleanPack
  recipes:
    - Plunger
    - MopBucket
    - SoapNT #imp recipe

- type: latheRecipePack
  id: BotanyPack
  recipes:
    - DiseaseSwab
    - HydroponicsToolMiniHoe
    - HydroponicsToolScythe
    - HydroponicsToolHatchet
    - HydroponicsToolSpade
    - HydroponicsToolClippers
    - Shovel
    - PlantBag #imp recipe

- type: latheRecipePack
  id: BarPack
  recipes:
    - DrinkShaker #imp recipe
    - DrinkJigger #imp recipe
    - DrinkFlaskBar #imp recipe
    - DrinkVacuumFlask #imp recipe
    - DrinkTeapotEmpty # imp recipe
    - DrinkTeacupEmpty #imp recipe
    - DrinkWaterBottleEmpty #imp recipe
    - Pitcher #imp recipe
    - BarSpoon #imp recipe
    - DrinkDisposableCup #imp recipe

- type: latheRecipePack
  id: KitchenPack
  recipes:
    - KitchenKnife
    - RollingPin #imp recipe
    - Fork #imp recipe
    - Spoon #imp recipe
    - ForkPlastic #imp recipe
    - SpoonPlastic #imp recipe
    - PairedChopsticks #imp recipe

- type: latheRecipePack
  id: ServiceMiscPack
  recipes:
    - Dropper
    - ClothingHeadHatCone
    - SprayPainter
    - FlashlightLantern

# Dynamic

- type: latheRecipePack
  id: CleanPackDynamic
  recipes:
    - MegaSprayBottle
    - AdvMopItem
    - WeaponSprayNozzle
    - ClothingBackpackWaterTank
    - CleanerGrenade

- type: latheRecipePack
  id: ServiceMiscPackDynamic
  recipes:
    - FishingRod #imp recipe

# Emagged

- type: latheRecipePack
  id: ServiceEmagged
  recipes:
    - ButchCleaver
