# Base prototypes

- type: latheRecipe
  abstract: true
  id: BaseServiceItemsRecipe
  categories:
  - KitchenNF
  completetime: 1
  materials:
    Steel: 75

- type: latheRecipe
  id: CondimentCupDispenser
  result: CondimentCupDispenser
  parent: BaseServiceItemsRecipe
  applyMaterialDiscount: false

- type: latheRecipe
  id: CondimentCup
  result: CondimentCup
  parent: BaseServiceItemsRecipe
  completetime: 0.1
  applyMaterialDiscount: false
  materials:
    Steel: 10

- type: latheRecipe
  id: FoodCondimentSqueezeBottleClear
  result: FoodCondimentSqueezeBottleClear
  parent: BaseServiceItemsRecipe
  applyMaterialDiscount: false
  materials:
    Plastic: 50
