- type: entity
  id: ElectricRangeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: oven machine board
  description: A machine printed circuit board for an oven.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: KitchenElectricRange
    stackRequirements:
      Capacitor: 3
      Steel: 5
      Glass: 2
      Cable: 4

- type: entity
  id: SyndicateElectricRangeMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: syndicate oven machine board
  description: A machine printed circuit board for an syndicate oven.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: SyndicateKitchenElectricRange
    stackRequirements:
      Capacitor: 3
      Steel: 5
      Glass: 2
      Cable: 4

- type: entity
  id: KitchenAssemblerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: food-o-mat machine board
  description: A machine printed circuit board for a Food-O-Mat, suitable for a kitchen.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: KitchenAssembler
    stackRequirements:
      Capacitor: 1
      Glass: 2
      Cable: 2

- type: entity
  id: MedicalAssemblerMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: medical assembler machine board
  description: A machine printed circuit board for a medical assembler.
  components:
  - type: Sprite
    state: medical
  - type: MachineBoard
    prototype: MedicalAssembler
    stackRequirements:
      Capacitor: 3
      Steel: 5
      Glass: 2
      Cable: 4

# Removed from upstream definitions

- type: entity
  id: CondimentDispenserCircuitboard
  parent: BaseMachineCircuitboard
  name: condiment dispenser machine board
  description: A machine printed circuit board for a condiment dispenser.
  components:
  - type: Sprite
    state: service
  - type: MachineBoard
    prototype: CondimentDispenserEmpty
    stackRequirements:
      Steel: 5
      MatterBin: 1
    tagRequirements:
      GlassBeaker:
        amount: 1
        defaultPrototype: Beaker
